server:
  port: 9001

spring:
  application:
    #会自动根据服务名拉取dataid对应的配置文件，如果服务名和dataid不一致，就需要手动指定dataid
    name: nacos-config
  cloud:
    nacos:
      discovery:
        server-addr: server:80
        namespace: public