server:
  port: 8901
  servlet:
    context-path: /consumer-nacos-loadbalancer-feign
spring:
  application:
    name: consumer-nacos-loadbalancer-feign
  cloud:
    nacos:
      discovery:
        server-addr: server:80

provider-nacos-url: http://provider-nacos/provider-nacos  #服务名/上下文

