server:
  port: 9301
spring:
  application:
    name: gateway-nacos
  cloud:
    nacos:
      discovery:
        server-addr: server:80
    gateway:
      globalcors:
        cors-configurations:
          # 全局允许跨域访问
            '[/**]':
              allow-credentials: true
              allowed-origins: "*"
              allowed-headers: "*"
              allowed-methods:
                - OPTIONS
                - GET
                - POST
                - PUT
                - DELETE
      routes:
        - id: provider-nacos
          uri: lb://provider-nacos
          predicates:
            - Path=/gateway-provider-nacos/**
            - Method=GET
          filters:
            - StripPrefix=1
logging:
  level:
    org.springframework.cloud.gateway: debug
