server:
  port: 9402
spring:
  application:
    name: dubbo-nacos-consumer
  cloud:
    nacos:
      discovery:
        server-addr: server:80
# Dubbo服务配置
dubbo:
  scan:
    base-packages: me.chenjd.demo.cloud.alibaba
  registry:
    address: nacos://server:80
  cloud:
    subscribed-services: dubbo-nacos-provider