server:
    port: 8501
spring:
    application:
        name: config-server-bus
    cloud:
        config:
            server:
                git:
                    uri: https://github.com/forezp/SpringcloudConfig
                    username:
                    password:
                    search-paths: respo
eureka:
    client:
        register-with-eureka: true
        fetch-registry: true
        service-url:
            defaultZone: http://sa:1@registry1:8001/eureka/,http://sa:1@registry2:8002/eureka/,http://sa:1@registry3:8003/eureka/