server:
  port: 9101
spring:
  application:
    name: sentinel-feign
  cloud:
    nacos:
      discovery:
        server-addr: server:80
    sentinel:
      log:
        dir: ./alibaba-sentinel-feign/logs
      datasource:
        ds1:
           nacos:
             server-addr: server:80
             data-id: sentinel-feign
             group-id: DEFAULT_GROUP
             data-type: json
             rule-type: flow
#      transport:
#        dashboard: server:9111
#        port: 9112
#      eager: true
feign:
  sentinel:
    enabled: true
