server:
  port: 9401
spring:
  application:
    name: dubbo-nacos-provider
  cloud:
    nacos:
      discovery:
        server-addr: server:80
# Dubbo服务配置
dubbo:
  scan:
    base-packages: me.chenjd.demo.cloud.alibaba
  registry:
    address: nacos://server:80