server:
    port: 8002
eureka:
    instance:
        hostname: cloud-registry2
    client:
        service-url:
            defaultZone: http://cloud-registry1:8001/eureka/,http://cloud-registry3:8003/eureka/
    server:
        enable-self-preservation: false
#        eviction-interval-timer-in-ms: 5000
