server:
    port: 8002
eureka:
    instance:
        hostname: registry2
    client:
#        fetch-registry: false
#        register-with-eureka: false
        service-url:
            defaultZone: http://sa:1@registry1:8001/eureka/,http://sa:1@registry3:8003/eureka/
    server:
        enable-self-preservation: false
#        eviction-interval-timer-in-ms: 5000
