server:
    port: 8003
eureka:
    instance:
        hostname: cloud-registry3
    client:
        service-url:
            defaultZone: http://cloud-registry1:8001/eureka/,http://cloud-registry2:8002/eureka/
    server:
        enable-self-preservation: false
#        eviction-interval-timer-in-ms: 5000

