server:
    port: 8001
eureka:
    instance:
        hostname: cloud-registry1
    client:
        service-url:
            defaultZone: http://cloud-registry2:8002/eureka/,http://cloud-registry3:8003/eureka/
    server:
        enable-self-preservation: false
#        eviction-interval-timer-in-ms: 5000
