server:
    port: 8003
eureka:
    instance:
        hostname: registry3
    client:
#        fetch-registry: false
#        register-with-eureka: false
        service-url:
            defaultZone: http://sa:1@registry1:8001/eureka/,http://sa:1@registry2:8002/eureka/
    server:
        enable-self-preservation: false
#        eviction-interval-timer-in-ms: 5000

